// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7b8Rp58oXcxTrjU9dUPK5zsMb9ypDaz0',
    appId: '1:153043837466:android:e973b89df78a55e91067a3',
    messagingSenderId: '153043837466',
    projectId: 'onlab1',
    storageBucket: 'onlab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfOJemHzuuA5pM3TcwfBRaqS9EoTnSfjg',
    appId: '1:153043837466:ios:cdb34eb3eaf99b251067a3',
    messagingSenderId: '153043837466',
    projectId: 'onlab1',
    storageBucket: 'onlab1.appspot.com',
    androidClientId: '153043837466-b71a2n8dib9kvrvb4niqoghhna44t613.apps.googleusercontent.com',
    iosClientId: '153043837466-5isre0ftdd7g4vgsoc5cja1gke5fv0kh.apps.googleusercontent.com',
    iosBundleId: 'hu.franciskav.onlab1',
  );
}
